# Bag of Words and TF-IDF
Below, we'll look at three useful methods of vectorizing text.
- `CountVectorizer` - Bag of Words
- `TfidfTransformer` - TF-IDF values
- `TfidfVectorizer` - Bag of Words AND TF-IDF values

Let's first use an example from earlier and apply the text processing steps we saw in this lesson.

In [1]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [2]:
corpus = ["The first time you see The Second Renaissance it may look boring.",
        "Look at it at least twice and definitely watch part 2.",
        "It will change your view of the matrix.",
        "Are the human people the ones who started the war?",
        "Is AI a bad thing ?"]

In [19]:
len(corpus)

5

In [3]:
stop_words = stopwords.words("english")
lemmatizer = WordNetLemmatizer()

Use the skills you learned so far to create a function `tokenize` that takes in a string of text and applies the following:
- case normalization (convert to all lowercase)
- punctuation removal
- tokenization, lemmatization, and stop word removal using `nltk`

Feel free to refer back to previous sections to complete these steps!

In [4]:
def tokenize(text):
    # normalize case and remove punctuation
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower())
    
    # tokenize text
    tokens = word_tokenize(text)
    
    # lemmatize andremove stop words
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return tokens

# `CountVectorizer` (Bag of Words)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

# initialize count vectorizer object
vect = CountVectorizer(tokenizer=tokenize)

In [11]:
# get counts of each token (word) in text data
X = vect.fit_transform(corpus)


In [13]:
print(vect.get_feature_names())

['2', 'ai', 'bad', 'boring', 'change', 'definitely', 'first', 'human', 'least', 'look', 'matrix', 'may', 'one', 'part', 'people', 'renaissance', 'second', 'see', 'started', 'thing', 'time', 'twice', 'view', 'war', 'watch']


In [15]:
# get the lenght of the list that has the featured names
y = vect.get_feature_names()
print(len(y))

25


In [14]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0]], dtype=int64)

In [18]:
# get the shape of the numpy array
X.toarray().shape

(5, 25)

The orginal text had **`5 sentences/documents`** each of which was presented as element in a list. 

The work on getting the bag of words resulted in **`25 featured words`**.

The document_term array has the size of **`5 rows`** *representing the 5 sentences we started with* and has **`25 columns`** *representing the total number of featured words*.

In [20]:
# view token vocabulary and counts
vect.vocabulary_

{'first': 6,
 'time': 20,
 'see': 17,
 'second': 16,
 'renaissance': 15,
 'may': 11,
 'look': 9,
 'boring': 3,
 'least': 8,
 'twice': 21,
 'definitely': 5,
 'watch': 24,
 'part': 13,
 '2': 0,
 'change': 4,
 'view': 22,
 'matrix': 10,
 'human': 7,
 'people': 14,
 'one': 12,
 'started': 18,
 'war': 23,
 'ai': 1,
 'bad': 2,
 'thing': 19}

# `TfidfTransformer`

In [21]:
from sklearn.feature_extraction.text import TfidfTransformer

# initialize tf-idf transformer object
transformer = TfidfTransformer(smooth_idf=False)

In [22]:
# use counts from count vectorizer results to compute tf-idf values
tfidf = transformer.fit_transform(X)

In [26]:
print(tfidf)

  (0, 6)	0.364195473106
  (0, 20)	0.364195473106
  (0, 17)	0.364195473106
  (0, 16)	0.364195473106
  (0, 15)	0.364195473106
  (0, 11)	0.364195473106
  (0, 9)	0.267453924226
  (0, 3)	0.364195473106
  (1, 9)	0.28717647778
  (1, 8)	0.391051929759
  (1, 21)	0.391051929759
  (1, 5)	0.391051929759
  (1, 24)	0.391051929759
  (1, 13)	0.391051929759
  (1, 0)	0.391051929759
  (2, 4)	0.57735026919
  (2, 22)	0.57735026919
  (2, 10)	0.57735026919
  (3, 7)	0.4472135955
  (3, 14)	0.4472135955
  (3, 12)	0.4472135955
  (3, 18)	0.4472135955
  (3, 23)	0.4472135955
  (4, 1)	0.57735026919
  (4, 2)	0.57735026919
  (4, 19)	0.57735026919


Similar to the Bag of words matrix size (CountVectorizer). 

The difference is that the presented elements for each word is the **count it appreared in each doc/sum of all counts in all documents**.

In [23]:
# convert sparse matrix to numpy array to view
tfidf.toarray()

array([[ 0.        ,  0.        ,  0.        ,  0.36419547,  0.        ,
         0.        ,  0.36419547,  0.        ,  0.        ,  0.26745392,
         0.        ,  0.36419547,  0.        ,  0.        ,  0.        ,
         0.36419547,  0.36419547,  0.36419547,  0.        ,  0.        ,
         0.36419547,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.39105193,  0.        ,  0.        ,  0.        ,  0.        ,
         0.39105193,  0.        ,  0.        ,  0.39105193,  0.28717648,
         0.        ,  0.        ,  0.        ,  0.39105193,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.39105193,  0.        ,  0.        ,  0.39105193],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.57735027,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.57735027,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0

In [25]:
tfidf.toarray().shape

(5, 25)

# `TfidfVectorizer`
`TfidfVectorizer` = `CountVectorizer` + `TfidfTransformer`

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

# initialize tf-idf vectorizer object
vectorizer = TfidfVectorizer()

In [28]:
# compute bag of word counts and tf-idf values
X = vectorizer.fit_transform(corpus)

In [29]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.30298183,  0.        ,  0.        ,  0.30298183,  0.        ,
         0.        ,  0.20291046,  0.        ,  0.24444384,  0.        ,
         0.30298183,  0.        ,  0.        ,  0.        ,  0.        ,
         0.30298183,  0.30298183,  0.30298183,  0.        ,  0.40582093,
         0.        ,  0.30298183,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.30298183,  0.        ],
       [ 0.        ,  0.30015782,  0.        ,  0.60031564,  0.        ,
         0.        ,  0.        ,  0.30015782,  0.        ,  0.        ,
         0.        ,  0.20101919,  0.30015782,  0.24216544,  0.        ,
         0.        ,  0.        ,  0.        ,  0.30015782,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.30015782,  0.        ,  0.        ,
         0.30015782,  0.        ,  0.        ,  0.